### ISSUE TITLE
设计问题

### ISSUE THREAD

**Issue by Meowcolm024** [HFerZHY/WikiSolubility-Project#1]
本来以为是程序直接爬Wikipedia的内容，其实按道理来说直接爬取Wikipedia的内容会更好（不过要联网）
然后其实我感觉data完全没必要整合在源码里，如果整合data的话会使修改数据变得非常麻烦，还要重新release一次，感觉直接来个data.txt就可以完事了OwO
三班 LYC 敬上

**Comment by HFerZHY** [comment]
我有个单独的爬虫，但是没传上来，而且一开始就打算做成离线的程序，所以就扔进代码里面了，0.2.1里面把数据单独装进一个py里面了，要更新数据的话我到时候改一下爬虫然后传上来让它直接改WSdata.py就好了

**Comment by eastonman** [comment]
@HFerZHY 将二进制文件放到源码里面是不明智的选择。
通常而言这会导致项目体积巨大。
发布的二进制文件应当使用release附件的形式。
将不同版本的源码采用不同后缀区分也是不明智的。
git会保留所有历史版本。
能不给我push权限。

**Comment by HFerZHY** [comment]
怎么给

**Comment by eastonman** [comment]
collabrator

**Comment by eastonman** [comment]
我已将master分支重构
